# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-13 12:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_auto_20160313_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='courses',
            name='start_date',
            field=models.DateField(),
        ),
    ]
